#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATED_DIR = REPO_ROOT / "docs" / "generated"


def run(cmd: list[str], cwd: Path | None = None) -> str:
    proc = subprocess.run(cmd, cwd=cwd, check=True, capture_output=True, text=True)
    return proc.stdout


def load_inventory(args: argparse.Namespace) -> dict[str, Any]:
    if args.inventory_file:
        return json.loads(Path(args.inventory_file).read_text(encoding="utf-8"))
    if args.inventory_json:
        return json.loads(args.inventory_json)
    out = run(["nix", "eval", "--json", ".#docInventory"], cwd=REPO_ROOT)
    return json.loads(out)


def rel(p: Path) -> str:
    return p.relative_to(REPO_ROOT).as_posix()


def importable_children(dir_path: Path) -> list[Path]:
    items: list[Path] = []
    for child in sorted(dir_path.iterdir(), key=lambda p: p.name):
        if child.name == "default.nix":
            continue
        if child.is_dir():
            items.append(child)
        elif child.is_file() and child.suffix == ".nix":
            items.append(child)
    return items


def tree_section(title: str, path: Path) -> str:
    lines = [f"## {title}", "", f"- Root: `{rel(path)}`", ""]
    children = importable_children(path)
    if not children:
        lines.append("- (empty)")
        lines.append("")
        return "\n".join(lines)
    for child in children:
        kind = "dir" if child.is_dir() else "file"
        lines.append(f"- `{rel(child)}` ({kind})")
    lines.append("")
    return "\n".join(lines)


def format_list(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value)


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(["---"] * len(headers)) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def build_architecture_md(inventory: dict[str, Any]) -> str:
    outputs = inventory.get("outputs", {})
    systems = inventory.get("systems", {})
    fragments = outputs.get("platformFragments", {})

    lines = [
        "# Generated Architecture Inventory",
        "",
        "This file is generated by `scripts/docs/generate.py`. Do not edit manually.",
        "",
        "## Flake Top-level Outputs",
        "",
        "- " + "\n- ".join(f"`{name}`" for name in outputs.get("topLevel", [])),
        "",
        "## Platform Systems",
        "",
        f"- Darwin systems: `{', '.join(systems.get('darwin', []))}`",
        f"- NixOS systems: `{', '.join(systems.get('nixos', []))}`",
        f"- All systems: `{', '.join(systems.get('all', []))}`",
        "",
        "## Platform Fragment Entrypoints",
        "",
    ]
    for system, fragment_dir in sorted(fragments.items()):
        lines.append(f"- `{system}` -> `{fragment_dir}`")
    lines.extend(
        [
            "",
            "## Generated Docs",
            "",
            "- `docs/generated/hosts.md`",
            "- `docs/generated/modules.md`",
            "- `docs/generated/checks-and-commands.md`",
            "",
        ]
    )
    return "\n".join(lines)


def build_hosts_md(inventory: dict[str, Any]) -> str:
    hosts = inventory.get("hosts", [])
    rows: list[list[str]] = []
    for host in sorted(hosts, key=lambda h: (h.get("platform", ""), h.get("name", ""))):
        rows.append(
            [
                str(host.get("name", "")),
                str(host.get("platform", "")),
                str(host.get("system", "")),
                str(host.get("kind", "")),
                "true" if bool(host.get("enabled", False)) else "false",
                str(host.get("hostPath", "")),
                str(host.get("homePath", "")),
                format_list(host.get("roles", [])),
                format_list(host.get("tags", [])),
            ]
        )

    return "\n".join(
        [
            "# Generated Host Registry",
            "",
            "This file is generated from `.#docInventory` (which is backed by `hosts/registry.nix`).",
            "",
            markdown_table(
                ["name", "platform", "system", "kind", "enabled", "hostPath", "homePath", "roles", "tags"],
                rows,
            ),
            "",
        ]
    )


def build_modules_md() -> str:
    sections = [
        ("System Modules (base)", REPO_ROOT / "modules" / "base"),
        ("System Modules (darwin)", REPO_ROOT / "modules" / "darwin"),
        ("Home Modules (base)", REPO_ROOT / "home" / "base"),
        ("Home Modules (darwin)", REPO_ROOT / "home" / "darwin"),
        ("Home Modules (nixos)", REPO_ROOT / "home" / "nixos"),
        ("Output Fragments (darwin)", REPO_ROOT / "outputs" / "aarch64-darwin" / "fragments"),
        ("Output Fragments (nixos)", REPO_ROOT / "outputs" / "x86_64-linux" / "fragments"),
        ("Output Helpers", REPO_ROOT / "outputs" / "lib"),
    ]
    lines = [
        "# Generated Module and Output Index",
        "",
        "This file is generated by `scripts/docs/generate.py` from the repository tree.",
        "",
    ]
    for title, path in sections:
        lines.append(tree_section(title, path))
    return "\n".join(lines).rstrip() + "\n"


def build_checks_md(inventory: dict[str, Any]) -> str:
    checks_by_system = inventory.get("checks", {})
    systems = inventory.get("systems", {}).get("all", [])
    rows: list[list[str]] = []
    for system in systems:
        rows.append([system, ", ".join(checks_by_system.get(system, []))])

    local_darwin_defaults = [
        "nix flake check --no-build",
        "nix build --no-link .#checks.aarch64-darwin.smoke-eval",
        "nix build --no-link .#checks.aarch64-darwin.docs-sync",
        "nix build --no-link .#checks.aarch64-darwin.pre-commit",
        "nix eval --json .#docInventory",
        "python3 scripts/docs/generate.py --write",
        "python3 scripts/docs/generate.py --check",
    ]
    ci_or_optional_linux = [
        "nix build --no-link .#checks.x86_64-linux.smoke-eval",
        "nix build --no-link .#checks.x86_64-linux.docs-sync",
        "nix build --no-link .#checks.x86_64-linux.pre-commit",
    ]
    remote_iso_build = [
        "scripts/build-nixos-iso-remote.sh --host <ssh-host> --remote-dir <remote-dir> --iso shaka-manual-installer-iso",
        "scripts/build-nixos-iso-remote.sh --dry-run --host <ssh-host> --remote-dir <remote-dir>",
    ]

    lines = [
        "# Generated Checks and Commands",
        "",
        "This file is generated by `scripts/docs/generate.py` and `.#docInventory`.",
        "",
        "## Check Matrix",
        "",
        markdown_table(["system", "checks"], rows),
        "",
        "## Local Darwin Defaults",
        "",
    ]
    lines.extend(f"- `{cmd}`" for cmd in local_darwin_defaults)
    lines.extend(
        [
            "",
            "## CI / Optional Linux Checks",
            "",
        ]
    )
    lines.extend(f"- `{cmd}`" for cmd in ci_or_optional_linux)
    lines.extend(
        [
            "",
            "## Remote ISO Build",
            "",
        ]
    )
    lines.extend(f"- `{cmd}`" for cmd in remote_iso_build)
    lines.append("")
    return "\n".join(lines)


BACKTICK_RE = re.compile(r"`([^`]+)`")


def extract_relative_path_tokens(markdown_text: str) -> list[str]:
    tokens: list[str] = []
    for token in BACKTICK_RE.findall(markdown_text):
        if " " in token:
            continue
        if token.startswith(("/", "~", ".#", "http://", "https://", "--")):
            continue
        if "*" in token or "<" in token or ">" in token:
            continue
        if token.startswith("#"):
            continue
        if token in {"bash", "mermaid", "json", "nix"}:
            continue
        if "://" in token:
            continue
        base = token.split(":", 1)[0]
        if "/" not in base and "." not in base:
            continue
        if base.startswith("."):
            continue
        known_prefixes = (
            "docs/",
            "scripts/",
            "modules/",
            "home/",
            "hosts/",
            "outputs/",
            "lib/",
            "vars/",
            "misc/",
            ".github/",
            "README.md",
            "DEPLOYMENT.md",
            "MIGRATION.md",
            "flake.nix",
            "flake.lock",
        )
        if not base.startswith(known_prefixes):
            continue
        tokens.append(base)
    return tokens


def validate_doc_paths() -> list[str]:
    markdown_files = [
        REPO_ROOT / "README.md",
        REPO_ROOT / "docs" / "README.md",
        REPO_ROOT / "DEPLOYMENT.md",
    ]
    errors: list[str] = []
    for md_file in markdown_files:
        text = md_file.read_text(encoding="utf-8")
        for token in extract_relative_path_tokens(text):
            candidate = REPO_ROOT / token
            if candidate.exists():
                continue
            # Allow doc-generated targets before first generation/write in the same run.
            if token.startswith("docs/generated/"):
                continue
            errors.append(f"{rel(md_file)} references missing path `{token}`")
    return sorted(set(errors))


def expected_files(inventory: dict[str, Any]) -> dict[Path, str]:
    return {
        GENERATED_DIR / "architecture.md": build_architecture_md(inventory),
        GENERATED_DIR / "hosts.md": build_hosts_md(inventory),
        GENERATED_DIR / "modules.md": build_modules_md(),
        GENERATED_DIR / "checks-and-commands.md": build_checks_md(inventory),
    }


def write_mode(inventory: dict[str, Any]) -> int:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    changed: list[str] = []
    for path, content in expected_files(inventory).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            path.write_text(content, encoding="utf-8")
            changed.append(rel(path))
    path_errors = validate_doc_paths()
    if changed:
        print("Updated generated docs:")
        for item in changed:
            print(f"- {item}")
    else:
        print("Generated docs already up to date.")
    if path_errors:
        print("Documentation path reference errors:", file=sys.stderr)
        for err in path_errors:
            print(f"- {err}", file=sys.stderr)
        return 1
    return 0


def check_mode(inventory: dict[str, Any]) -> int:
    failures: list[str] = []
    for path, content in expected_files(inventory).items():
        if not path.exists():
            failures.append(f"Missing generated file: {rel(path)}")
            continue
        current = path.read_text(encoding="utf-8")
        if current != content:
            failures.append(f"Out-of-date generated file: {rel(path)}")
    failures.extend(validate_doc_paths())
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    print("Documentation is in sync.")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate and validate Nix repo docs")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="Write generated docs")
    mode.add_argument("--check", action="store_true", help="Check generated docs are up to date")
    parser.add_argument("--inventory-file", help="Path to docInventory JSON file")
    parser.add_argument("--inventory-json", help="Raw docInventory JSON string")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
      inventory = load_inventory(args)
    except subprocess.CalledProcessError as exc:
      sys.stderr.write(exc.stderr)
      return exc.returncode
    if args.write:
        return write_mode(inventory)
    return check_mode(inventory)


if __name__ == "__main__":
    raise SystemExit(main())
